"""Add availability_status and local_path to Episode

Revision ID: 1d6d11d0ccc6
Revises: 703c9228a324
Create Date: 2025-05-03 20:36:14.120806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6d11d0ccc6'
down_revision: Union[str, None] = '703c9228a324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episoden', sa.Column('availability_status', sa.Enum('NOT_AVAILABLE', 'AVAILABLE_ONLINE', 'OWNED_LOCALLY', 'OWNED_AND_AVAILABLE_ONLINE', name='episodeavailabilitystatus'), nullable=False))
    op.add_column('episoden', sa.Column('local_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episoden', 'local_path')
    op.drop_column('episoden', 'availability_status')
    # ### end Alembic commands ###
