"""Erweitere Anime-Modell und füge Relationen hinzu

Revision ID: 3e368c825ee6
Revises: 
Create Date: 2025-05-03 17:50:05.198033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3e368c825ee6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_anime_id', sa.Integer(), nullable=False),
    sa.Column('target_anime_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['source_anime_id'], ['animes.id'], ),
    sa.ForeignKeyConstraint(['target_anime_id'], ['animes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anime_relations_id'), 'anime_relations', ['id'], unique=False)
    op.add_column('animes', sa.Column('original_titel', sa.String(length=255), nullable=True))
    op.add_column('animes', sa.Column('synonyme', sa.String(length=500), nullable=True))
    op.add_column('animes', sa.Column('typ', sa.String(length=50), nullable=True))
    op.add_column('animes', sa.Column('jahr', sa.Integer(), nullable=True))
    op.add_column('animes', sa.Column('episoden_anzahl', sa.String(length=50), nullable=True))
    op.add_column('animes', sa.Column('laufzeit', sa.String(length=50), nullable=True))
    op.add_column('animes', sa.Column('hauptgenre', sa.String(length=100), nullable=True))
    op.add_column('animes', sa.Column('nebengenres', sa.String(length=255), nullable=True))
    op.add_column('animes', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('animes', sa.Column('anime_loads_id', sa.String(length=255), nullable=True))
    op.add_column('animes', sa.Column('anisearch_url', sa.String(length=255), nullable=True))
    op.add_column('animes', sa.Column('cover_image_data', sa.LargeBinary(), nullable=True))
    op.add_column('animes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('animes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('animes', 'status',
               existing_type=mysql.ENUM('watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch', collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('animes', 'anime_loads_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('animes', 'cover_image_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index('ix_animes_titel', table_name='animes')
    op.create_unique_constraint(None, 'animes', ['anime_loads_id'])
    op.drop_column('animes', 'hinzugefuegt_am')
    op.drop_column('animes', 'zuletzt_aktualisiert_am')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('zuletzt_aktualisiert_am', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True))
    op.add_column('animes', sa.Column('hinzugefuegt_am', mysql.TIMESTAMP(), server_default=sa.text('(now())'), nullable=True))
    op.drop_constraint(None, 'animes', type_='unique')
    op.create_index('ix_animes_titel', 'animes', ['titel'], unique=True)
    op.alter_column('animes', 'cover_image_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=True)
    op.alter_column('animes', 'anime_loads_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=512),
               existing_nullable=True)
    op.alter_column('animes', 'status',
               existing_type=mysql.ENUM('watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch', collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_column('animes', 'updated_at')
    op.drop_column('animes', 'created_at')
    op.drop_column('animes', 'cover_image_data')
    op.drop_column('animes', 'anisearch_url')
    op.drop_column('animes', 'anime_loads_id')
    op.drop_column('animes', 'tags')
    op.drop_column('animes', 'nebengenres')
    op.drop_column('animes', 'hauptgenre')
    op.drop_column('animes', 'laufzeit')
    op.drop_column('animes', 'episoden_anzahl')
    op.drop_column('animes', 'jahr')
    op.drop_column('animes', 'typ')
    op.drop_column('animes', 'synonyme')
    op.drop_column('animes', 'original_titel')
    op.drop_index(op.f('ix_anime_relations_id'), table_name='anime_relations')
    op.drop_table('anime_relations')
    # ### end Alembic commands ###
