"""Hinzufügen von Feldern für lokalen Import zu Anime und Episode

Revision ID: 4a45d02b028d
Revises: 2bbe6c1873d5
Create Date: 2025-05-04 18:10:51.656003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4a45d02b028d'
down_revision: Union[str, None] = '2bbe6c1873d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animes', sa.Column('imported_from_local', sa.Boolean(), nullable=True))
    op.add_column('animes', sa.Column('local_path', sa.String(length=500), nullable=True))
    op.add_column('animes', sa.Column('auto_update', sa.Boolean(), nullable=True))
    op.add_column('animes', sa.Column('last_scan_time', sa.DateTime(), nullable=True))
    op.alter_column('animes', 'titel_de',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
    op.drop_column('animes', 'original_titel')
    op.drop_column('animes', 'titel')
    op.add_column('episoden', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('episoden', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('episoden', sa.Column('resolution', sa.String(length=20), nullable=True))
    op.add_column('episoden', sa.Column('codec', sa.String(length=20), nullable=True))
    op.add_column('episoden', sa.Column('audio_format', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episoden', 'audio_format')
    op.drop_column('episoden', 'codec')
    op.drop_column('episoden', 'resolution')
    op.drop_column('episoden', 'file_hash')
    op.drop_column('episoden', 'file_size')
    op.add_column('animes', sa.Column('titel', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
    op.add_column('animes', sa.Column('original_titel', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True))
    op.alter_column('animes', 'titel_de',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               nullable=True)
    op.drop_column('animes', 'last_scan_time')
    op.drop_column('animes', 'auto_update')
    op.drop_column('animes', 'local_path')
    op.drop_column('animes', 'imported_from_local')
    # ### end Alembic commands ###
